# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from view.impl.PicLabel import PicQLabel


class Ui_select(object):
    def setupUi(self, select):
        select.setObjectName("select")
        select.resize(600, 400)
        # TMD怎么设置了个透明，调了一下午都没有界面
        self.gridLayout_2 = QtWidgets.QGridLayout(select)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = PicQLabel(select)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = PicQLabel(select)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_1 = PicQLabel(select)
        self.label_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_6 = PicQLabel(select)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_2 = PicQLabel(select)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = PicQLabel(select)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(select)
        QtCore.QMetaObject.connectSlotsByName(select)

    def retranslateUi(self, select):
        _translate = QtCore.QCoreApplication.translate
        select.setWindowTitle(_translate("select", "请选择推理类型："))
        self.label_5.setText(_translate("select", "CT腹膜后淋巴"))
        self.label_3.setText(_translate("select", "CT肝肿瘤"))
        self.label_1.setText(_translate("select", "CT肾肿瘤"))
        self.label_6.setText(_translate("select", "X线乳腺钼靶"))
        self.label_2.setText(_translate("select", "CT气胸"))
        self.label_4.setText(_translate("select", "X线气胸"))
